name: CICD DEPLOY NOTEBOOK

on:
  push:
    branches:
      - main


jobs:
  deploy_databricks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and install databricks-cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Configure DataBricks DEV CLI
        env:
          ADB_ACCESS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          ADB_URL: ${{ secrets.DATABRICKS_HOST }}
        run: |
          echo $ADB_ACCESS_TOKEN | databricks configure --host $ADB_URL --token $ADB_ACCESS_TOKEN

      - name: Create App Dir if it does not exist
        run: |
          databricks workspace mkdirs "/Workspace/Shared/notebooks/"

      - name: Clean Workspace
        run: |
          databricks workspace delete "/Workspace/Shared/notebooks/" --recursive

      - name: Copy to Workspace
        run: |
          databricks workspace import-dir --overwrite ./projeto/ "/Workspace/Shared/notebooks/"
