name: Databricks CICD

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest
    environment: PRD 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Databricks CLI
      run: |
        pip install databricks-cli
        databricks configure --token
        echo "Host: $DATABRICKS_HOST"
        echo "[DEFAULT]" > ~/.databrickscfg
        echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
        echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    - name: Copy files to Databricks Shared
      run: |
        # Exemplo de script para copiar arquivos para Databricks
        databricks fs cp --overwrite ./projeto /Workspace/Shared --recursive
