name: Databricks CICD

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Databricks CLI
      run: |
        pip install databricks-cli
        databricks configure --token
      env:
        DATABRICKS_HOST: "https://adb-574244322308102.2.azuredatabricks.net"
        DATABRICKS_TOKEN: "dapi59688b5a150ce0425bd5050821c5f410-3"

    - name: Copy files to Databricks Shared
      run: |
        # Exemplo de script para copiar arquivos para Databricks
        databricks fs cp --overwrite ./projeto /Workspace/Shared --recursive
